export const templatePdf = [
	{
		anschlag: {
			type: 'text',
			position: {
				x: 25,
				y: 86,
			},
			width: 157.75,
			height: 37.42,
			alignment: 'left',
			fontSize: 18,
			lineHeight: 1.32,
		},
		title: {
			type: 'text',
			position: {
				x: 25,
				y: 75.67,
			},
			width: 155.65,
			height: 7,
			alignment: 'left',
			fontName: 'calibriBold',
			fontSize: 18,
			lineHeight: 1.2,
		},
		date: {
			type: 'text',
			position: {
				x: 90,
				y: 124,
			},
			width: 60.93,
			height: 7,
			alignment: 'left',
			fontSize: 18,
			characterSpacing: 0,
			lineHeight: 1.2,
		},
		time: {
			type: 'text',
			position: {
				x: 90,
				y: 137,
			},
			width: 59.87,
			height: 7,
			alignment: 'left',
			fontSize: 18,
			characterSpacing: 0,
			lineHeight: 1.2,
		},
		location: {
			type: 'text',
			position: {
				x: 90,
				y: 147.5,
			},
			width: 59.61,
			height: 7,
			alignment: 'left',
			fontSize: 18,
			characterSpacing: 0,
			lineHeight: 1.2,
		},
		mitnehmen: {
			type: 'text',
			position: {
				x: 90,
				y: 158,
			},
			width: 91.88,
			height: 35.04,
			alignment: 'left',
			fontSize: 18,
			characterSpacing: 0,
			lineHeight: 1.2,
		},
		anschlagMail: {
			type: 'text',
			position: {
				x: 90,
				y: 204,
			},
			width: 73.1,
			height: 7,
			alignment: 'left',
			fontSize: 18,
			characterSpacing: 0,
			lineHeight: 1.2,
		},
		abmeldenBis: {
			type: 'text',
			position: {
				x: 25,
				y: 204,
			},
			width: 30.5,
			height: 7,
			alignment: 'left',
			fontName: 'calibriBold',
			fontSize: 18,
			characterSpacing: 0,
			lineHeight: 1.2,
		},
	},
];
